uses: actions/labeler@v5
on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]

 
 
nt8bridge:
  - "NT8Bridge/**"
strategies:
  - "Strategies/**"
portable:
  - "Abstractions/**"
  - "Common/**"
  - "Risk/**"
  - "Sizing/**"
  - "Session/**"
  - "Trailing/**"
  - "Diagnostics/**"
  - "Telemetry/**"
docs:
  - "Docs/**"
  - "**/*.md"
ci:
  - ".github/**"
tools:
  - "tools/**"
