nt8bridge:
  - changed-files:
      - any-glob-to-any-file: 'NT8Bridge/**'

strategies:
  - changed-files:
      - any-glob-to-any-file: 'Strategies/**'

portable:
  - changed-files:
      - any-glob-to-any-file: 'Abstractions/**'
      - any-glob-to-any-file: 'Common/**'
      - any-glob-to-any-file: 'Risk/**'
      - any-glob-to-any-file: 'Sizing/**'
      - any-glob-to-any-file: 'Session/**'
      - any-glob-to-any-file: 'Trailing/**'
      - any-glob-to-any-file: 'Diagnostics/**'
      - any-glob-to-any-file: 'Telemetry/**'

docs:
  - changed-files:
      - any-glob-to-any-file: 'Docs/**'
      - any-glob-to-any-file: '**/*.md'

ci:
  - changed-files:
      - any-glob-to-any-file: '.github/**'

tools:
  - changed-files:
      - any-glob-to-any-file: 'tools/**'
