name: Task
description: Small scoped task
labels: ["chore"]
assignees: ["CodexDev"]
body:
  - type: input
    id: outcome
    attributes: { label: Outcome (what changes) }
    validations: { required: true }
  - type: textarea
    id: steps
    attributes: { label: Steps / acceptance criteria }
