name: Auto-merge (squash, safe)

on:
  pull_request:
    types: [labeled, synchronize, reopened, ready_for_review]
  check_suite:
    types: [completed]
  status: {}

jobs:
  gate:
    name: Path gate
    runs-on: ubuntu-latest
    outputs:
      ok_to_merge: ${{ steps.decide.outputs.ok }}
    steps:
      - uses: actions/checkout@v4
      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            protected:
              - "NT8Bridge/**"
              - "Strategies/**"
              - "Risk/**"
              - "Session/**"
              - "tools/**"
              - ".github/**"
      - id: decide
        run: |
          if [ "${{ steps.filter.outputs.protected }}" = "true" ]; then
            echo "ok=false" >> $GITHUB_OUTPUT
          else
            echo "ok=true" >> $GITHUB_OUTPUT
          fi

  automerge:
    needs: gate
    if: >
      github.event.pull_request.draft == false &&
      contains(github.event.pull_request.labels.*.name, 'auto-merge') &&
      needs.gate.outputs.ok_to_merge == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
      - uses: peter-evans/auto-merge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          required-labels: auto-merge
