name: Guard & Build
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Optional PowerShell guard; warn if not available
      - name: Guard (optional)
        run: |
          if command -v pwsh >/dev/null 2>&1 && [ -f "./tools/guard.ps1" ]; then
            pwsh -NoLogo -NoProfile ./tools/guard.ps1 || true
          else
            echo "::warning::Skipping guard.ps1 (pwsh or script not found)"
          fi

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -c Release
      - name: Package SDK
        run: |
          mkdir -p dist package
          cp qa/summary.json package/ 2>/dev/null || true
          find Risk Config -maxdepth 2 -type f \( -name '*.json' -o -name '*.log' -o -name '*.config' \) -exec cp --parents {} package/ \; 2>/dev/null || true
          cp -r bin/Release package/bin 2>/dev/null || true
          zip -r dist/SDK.zip package
      - name: Upload QA summary (best-effort)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: qa-summary
          path: |
            qa/summary.json
            **/qa/summary.json
          if-no-files-found: warn
      - name: Upload SDK package
        uses: actions/upload-artifact@v4
        with:
          name: SDK
          path: dist/SDK.zip
          if-no-files-found: error
