name: PR Labeler
on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
