name: NT8 Guard (layout-aware)

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Mono (mcs)
        run: |
          sudo apt-get update
          sudo apt-get install -y mono-complete

      - name: Stage A — Abstractions only (if present)
        shell: bash
        run: |
          set -euo pipefail
          if [ -d Abstractions ]; then
            find Abstractions -name '*.cs' > files.txt || true
            if [ -s files.txt ]; then
              mcs -langversion:7.2 -target:library -out:stageA.dll @files.txt
            fi
          fi

      - name: Stage B — Core portable layers (auto-detect)
        shell: bash
        run: |
          set -euo pipefail
          DIRS=""
          for d in Abstractions Config Session Common Risk Sizing Trailing Diagnostics Telemetry; do
            [ -d "$d" ] && DIRS="$DIRS $d"
          done
          if [ -n "$DIRS" ]; then
            find $DIRS -name '*.cs' > files.txt || true
            if [ -s files.txt ]; then
              mcs -langversion:7.2 -r:System.Web.Extensions.dll -target:library -out:stageB.dll @files.txt
            fi
          fi

      - name: Fail on NinjaTrader types in portable layers
        shell: bash
        run: |
          set -euo pipefail
          PORTABLE_DIRS="Abstractions Common Risk Sizing Session Trailing Diagnostics Telemetry"
          bad=0
          for d in $PORTABLE_DIRS; do
            if [ -d "$d" ]; then
              if grep -R --line-number -E '(^|[^A-Za-z0-9_])NinjaTrader\.' "$d"; then
                echo "::error ::NinjaTrader types detected in portable layer: $d"
                bad=1
              fi
            fi
          done
          exit $bad

      - name: No root .cs files
        shell: bash
        run: |
          shopt -s nullglob
          root_cs=( *.cs )
          if [ ${#root_cs[@]} -gt 0 ]; then
            printf '%s\n' "${root_cs[@]}"
            echo "::error ::C# files found at repo root. Move them into proper folders."
            exit 1
          fi
