name: NT8 Guard

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run NT8 Guard
        run: python tools/nt8_guard.py --fail-on-warn

      - name: Install Mono (ensure mcs exists)
        run: |
          sudo apt-get update
          sudo apt-get install -y mono-complete
          mcs -version || true
          mono --version || true

      - name: Build Step 1 (Abstractions only)
        run: |
          mkdir -p build
          mcs -langversion:7.2 -target:library Abstractions/*.cs -out:build/sdk.abstractions.dll

      - name: Build Step 2 (Config + Session)
        run: |
          mcs -langversion:7.2 -target:library \
            Abstractions/*.cs Config/*.cs Session/*.cs \
            -r:/usr/lib/mono/4.5/System.Web.Extensions.dll \
            -out:build/sdk.step2.dll

      - name: Build Step 3 (Risk)
        run: |
          mcs -langversion:7.2 -target:library \
            Abstractions/*.cs Risk/*.cs \
            -out:build/sdk.step3.dll
            
      - name: Build Step 4 (Sizing)
        run: |
          mcs -langversion:7.2 -target:library \
            Abstractions/*.cs Sizing/*.cs \
            -out:build/sdk.step4.dll


      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: nt8-sdk-builds
          path: |
            build/sdk.abstractions.dll
            build/sdk.step2.dll
            build/sdk.step3.dll
