name: NT8 Guard
on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Run NT8 Guard
        run: |
          python tools/nt8_guard.py --fail-on-warn
