name: NT8 Guard (layout-aware)

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  guard:
    runs-on: ubuntu-latest
    container: mono:6.12
    steps:
      - uses: actions/checkout@v4

      - name: Stage A — Abstractions (best-effort)
        shell: bash
        run: |
set -euo pipefail
          if [ -d Abstractions ]; then
            mapfile -t files < <(find Abstractions -name "*.cs")
            if [ ${#files[@]} -gt 0 ]; then
              if mcs -langversion:7.2 -target:library -out:stageA.dll "${files[@]}"; then
                echo "Stage A compile OK"
              else
                echo "::warning ::Stage A compile failed; exiting."
              fi
            fi
          fi

      # -------- Stage B: Portable layers — best-effort (warn on failure) -----
      - name: Stage B — Portable layers (best-effort)
        shell: bash
        run: |
          set -u
          DIRS=()
          for d in Abstractions Config Session Common Risk Sizing Trailing Diagnostics Telemetry Facade; do
            [ -d "$d" ] && DIRS+=("$d")
          done
          if [ ${#DIRS[@]} -gt 0 ]; then
            mapfile -t files < <(find "${DIRS[@]}" -name "*.cs")
            if [ ${#files[@]} -gt 0 ]; then
              if mcs -langversion:7.2 -r:System.Web.Extensions.dll -target:library -out:stageB.dll "${files[@]}"; then
                echo "Stage B compile OK"
              else
                echo "::warning ::Stage B compile failed; exiting."
              fi
            fi
          fi

      # -------- Hard gate: NinjaTrader types in portable layers (FAIL) -------
      - name: Fail on NinjaTrader types in portable layers
        shell: bash
        run: |
          set -euo pipefail
          PORTABLE_DIRS="Abstractions Common Risk Sizing Session Trailing Diagnostics Telemetry"
          bad=0
          for d in $PORTABLE_DIRS; do
            if [ -d "$d" ]; then
              if grep -R --line-number -E '(^|[^A-Za-z0-9_])NinjaTrader\.' "$d"; then
                echo "::error ::NinjaTrader types detected in portable layer: $d"
                bad=1
              fi
            fi
          done
          exit $bad

      # -------- Temporary: root .cs files (WARN only) ------------------------
      - name: Root .cs files (TEMPORARY WARN ONLY)
        shell: bash
        run: |
          shopt -s nullglob
          root_cs=( *.cs )
          if [ ${#root_cs[@]} -gt 0 ]; then
            printf '%s\n' "${root_cs[@]}"
            echo "::warning ::C# files exist at repo root; move them into proper folders. (Warn-only temporarily.)"
          fi