name: NT8 Guard
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore || true

      - name: Build (non-fatal)
        run: dotnet build --no-restore -c Release || true

      - name: Guard (optional)
        run: |
          if command -v pwsh >/dev/null 2>&1 && [ -f "./tools/guard.ps1" ]; then
            pwsh -NoLogo -NoProfile ./tools/guard.ps1 || true
          else
            echo "::warning::Skipping guard.ps1 (pwsh or script not found)"
          fi

      - name: Test (optional)
        run: |
          if command -v pwsh >/dev/null 2>&1 && [ -f "./tools/test.ps1" ]; then
            pwsh -NoLogo -NoProfile ./tools/test.ps1 || true
          else
            echo "::warning::Skipping test.ps1 (pwsh or script not found)"
          fi

      - name: Upload QA summary
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: qa-summary
          path: |
            qa/summary.json
            **/qa/summary.json
          if-no-files-found: warn

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: |
            logs/**
            **/logs/**
          if-no-files-found: warn

  package:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Package SDK bundle
        run: |
          mkdir -p dist
          zip -r dist/sdk_bundle.zip ./bin ./docs/runbook.md qa/summary.json 2>/dev/null || true
      - name: Upload SDK bundle
        uses: actions/upload-artifact@v4
        with:
          name: sdk-bundle
          path: dist/sdk_bundle.zip
          if-no-files-found: error
