name: Package SDK
on:
  workflow_run:
    workflows: ["NT8 Guard"]
    types: [completed]
jobs:
  package:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Collect artifacts (best-effort)
        run: |
          mkdir -p dist
          mkdir -p qa || true
          test -f qa/summary.json || true
          zip -r dist/sdk_bundle.zip ./bin ./docs/runbook.md qa/summary.json 2>/dev/null || true
      - name: Upload SDK bundle
        uses: actions/upload-artifact@v4
        with:
          name: sdk-bundle
          path: dist/sdk_bundle.zip
          if-no-files-found: warn
