name: Portable SDK Guard

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  portable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore SDK.sln
      - name: Build
        run: dotnet build SDK.sln --no-restore -c Release
