name: QA PR Comment
on:
  workflow_run:
    workflows: ["NT8 Guard"]
    types: [completed]
jobs:
  comment:
    if: ${{ github.event.workflow_run.conclusion != 'cancelled' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 'lts/*' }
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Determine PR number
        id: pr
        run: |
          echo "pr=$(jq -r '.pull_requests[0].number // empty' <<< '${{ toJson(github.event.workflow_run) }}')" >> $GITHUB_OUTPUT
      - name: Skip if not a PR
        if: ${{ steps.pr.outputs.pr == '' }}
        run: echo "Not a PR run; skipping."
      - name: Post QA KPIs comment
        if: ${{ steps.pr.outputs.pr != '' }}
        run: ./scripts/post-qa-comment.sh "${{ steps.pr.outputs.pr }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
